# Site Settings
title: Lapio Team | The DSM Hacking Team
email: teamlapio@gmail.com
description: The Lapio is hacking & security team in DSM.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://blog.lapio.kr" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Lapio
user_description: The Lapio is hacking & security team in DSM.
disqus_username: Lapio

# Social Media
# Remove the item if you don't need it
github_username: Team-Lapio
facebook_username: LapioTeam
# twitter_username: https://fb.com/LapioTeam
# instagram_username: https://fb.com/LapioTeam
# linkedin_username: https://fb.com/LapioTeam
# medium_username: https://fb.com/LapioTeam

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
